spring:
  application:
    name: spaced-repetition-service
  config:
    import: optional:file:.env[.properties]
  profiles:
    default: dev
  datasource:
    url: ${DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

srs:
  algorithm: ${SRS_ALGORITHM:fsrs}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
